Error: Can't set headers after they are sent.
Stupid mistake. I was reporting an error, but instead of exit a function,
I was processing it further until I tried to send the same error again.

I've also added displaying a status to the new editor if the map request
ended with error.

https://github.com/cdaniel/wardleymapstool/issues/70